#!/bin/bash
yum install -y httpd
systemctl enable httpd
systemctl start httpd
yum install nagios -y
systemctl enable nagios
systemctl start nagios
setenforce 0
yum install -y nrpe
systemctl enable nrpe
systemctl start nrpe
yum install nagios-plugins-all -y
yum -y install nagios-plugins-nrpe

yum install -y nagios-selinux -y
systemctl restart nagios
setenforce 1

#todo: sed statements disabling the login process in /etc/nagios/cgi.cfg (enforcement = 0), and commenting out all authentication in /etc/httpd/conf.d/nagios.conf.
sed -i 's/use_authentication=1/use_authentication=0/g' /etc/nagios/cgi.cfg
sed -i 's/AuthName/#Authname/g' /etc/httpd/conf.d/nagios.conf
sed -i 's/AuthType/#AuthType/g' /etc/httpd/conf.d/nagios.conf
sed -i 's/AuthUserFile/#AuthUserFile/g' /etc/httpd/conf.d/nagios.conf
sed -i 's/Require/#Require valid/g' /etc/httpd/conf.d/nagios.conf


echo '########### NRPE CONFIG LINE #######################
define command{
command_name check_nrpe
command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
}' >> /etc/nagios/objects/commands.cfg
