#!/bin/bash

yum install -y nss-pam-ldapd nscd wget

#LDAP config stuff.

authconfig --enableldap --enableldapauth --ldapserver=ldap://10.142.0.2/ --ldapbasedn="dc=capstone,dc=local" --updateall 

#echo -e '\n
#URI ldap://10.142.0.2
#base dc=capstone,dc=local' >> /etc/openldap/ldap.conf

systemctl restart nscd

#NFS stuff starts here.

systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

#NFS LDAP integration begins here.
wget <file>

#Echoes in a cron job for automatic updating of LDAP clients.

echo "/var/nfsshare/testing   *(rw,sync)" >> /etc/exports

systemctl restart nfs-server
