#!/bin/bash

yum install nfs-utils openldap openldap-clients -y

#LDAP config stuff.

#sed -i 's/passwd:     files sss/passwd:     files ldap/g' /etc/nsswitch.conf
#sed -i 's/shadow:     files sss/shadow:     files ldap/g' /etc/nsswitch.conf
#sed -i 's/group:      files sss/group:     files ldap/g' /etc/nsswitch.conf
#sed -i 's/automount:  files nisplus sss/automount:  files nisplus ldap/g' /etc/nsswitch.conf

#authconfig --enableldap --enableldapauth --ldapserver=ldap://10.142.0.2/ --ldapbasedn="base dc=capstone,dc=local" --enablecache --disablefingerprint --kickstart 

echo -e '\n
URI ldap://10.142.0.2
base dc=capstone,dc=local' >> /etc/openldap/ldap.conf

systemctl restart nscd

#echo -e 'LDAP_URI="ldap://10.142.0.2/"
#SEARCH_BASE="ou=base dc=capstone,dc=local"
#MAP_OBJECT_CLASS="nisMap"
#ENTRY_OBJECT_CLASS="nisObject"
#MAP_ATTRIBUTE="nisMapName"
#ENTRY_ATTRIBUTE="cn"' >> /etc/sysconfig/autofs

systemctl restart nscd

# ^ Currently broken?

#NFS stuff starts here.

mkdir /var/nfsshare
mkdir /var/nfsshare/devstuff
mkdir /var/nfsshare/testing
mkdir /var/nfsshare/home_dirs

#Free permissions on /var/nfsshare. Shares can be locked up on an individual basis if needed.
chmod -R 777 /var/nfsshare

systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

echo "/var/nfsshare/home_dirs *(rw,sync,no_all_squash)
/var/nfsshare/devstuff  *(rw,sync,no_all_squash)
/var/nfsshare/testing   *(rw,sync,no_all_squash)" >> /etc/exports

systemctl restart nfs-server
