#!/bin/bash

if [ -e /etc/httpd/conf.d/cacti.conf ]; then exit 0; fi

export DEBIAN_FRONTEND=noninteractive
apt-get --yes install libpam-ldap nscd
wget https://raw.githubusercontent.com/Tedtanium/NTI-470-Capstone-Project/master/machine-scripts/configs/ldap/ldap_debconf

while read line; do echo "$line" | debconf-set-selections; done < ldap_debconf

apt-get install -y libpam-ldap nscd

sed -i 's/compat/compat ldap/g' /etc/nsswitch.conf

sed -i 's/PasswordAuthentication no/PasswordAuthentication Yes/g' /etc/ssh/sshd_config

systemctl enable nscd
/etc/init.d/nscd restart

export DEBIAN_FRONTEND=interactive

#Just in case.
sed -i 's,uri ldapi:///,uri ldap://10.142.0.2,g' /etc/ldap.conf
sed -i 's/base dc=example,dc=net/base dc=capstone,dc=local/g' /etc/ldap.conf
