#!/bin/bash

#Made to work with both Ubuntu and CentOS (yum and apt).
apt-get install nfs-client -y
yum install nfs-client -y

mkdir /mnt/test 

#points the NFS client towards the server, then specifies the directory to be mounted. 
#Then specifies how it'll show as a local directory, then specifies NFS usage.
echo "10.142.0.8:/home/ /ldap/ nfs" >> /etc/fstab

mount -a
