#!/bin/bash

#This should be run every minute as a cron job.

#Greps for LDAP users, and stores their usernames in a file. 
#This one overwrites the old ones, as otherwise the function would get drastically longer with each and every run of it.
getent passwd | grep 500 | awk -F ":" '{print $1}' > ldap-users

#Stores username as $uservariable.

#Starts for loop.

#Check to see if /home/$uservariable exists; if not then move onto the next section of the for loop (How do?)

#Creates user directory in /home/$uservariable
mkdir /home/$uservariable

#Echoes user directory into the /etc/exports file, where it will be shared via NFS. (UNFINISHED)
echo "/home/$uservariable   *(rw,sync)" >> /etc/exports

#Changes permissions of /home/$uservariable share.
chmod /home/$uservariable 0700

#Changes ownership of /home/$uservariable to the user.
chown /home/$uservariable $uservariable

#End of for loop.
